### PR TITLE
Added launch config and fixed filter bug.

### LINKED ISSUE #131: Unpause nodes before attempting to filter.
Make sure paused is false before attempting to filter columns in the result table component since filter information is sometime based on query results.

### PR DESCRIPTION
**Pull request by geosp**
Fixes #131

### CODE REVIEW

**Comment by decrapifier** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>The README has not been updated. Please update the README.</td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>Could not find any browser results.</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>We were able to automatically fix some formatting issues in this PR for you!</td>
    </tr>
  </tbody>
</table>


### Some things that were possibly fixed:

- Code that could be fixed via the --fix flag
- Formatting that could be fixed by prettier

Take a look at this commit to see what happened in detail: adbc365b1aa2652e7caf08b1879d2965e41cfeeb


And look at this wiki page to see the reasoning behind the ESLint rules: https://github.com/smartprocure/eslint-config-smartprocure/wiki/Rules-and-Why-We-Chose-Them
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 96b9b73fec89726c5b9a310f6b87d6f44e09b85a
</p>

File: src/exampleTypes/ResultTable.js [hunk 1]
```diff
@@ -105,6 +105,7 @@ let Header = withStateLens({ popover: false, adding: false, filtering: false })(
       criteria && _.find({ field }, tree.getNode(criteria).children)
     let filter = () => {
       if (!filterNode) addFilter(field)
+      filterNode.paused = false
```
Comment (daedalus28) [inline src/exampleTypes/ResultTable.js]: This is not safe to do because there could be pending updates. In general, we should never be modifying node properties outside of actions that dispatch the appropriate events. The right approach here is to do a mutate like

```js
tree.mutate(node.path, { paused: false })
```

You can see an example of us doing that in this repo here: https://github.com/smartprocure/contexture-react/blob/master/src/FilterList.js#L19

File: CHANGELOG.md [hunk 2]
```diff
@@ -1,3 +1,7 @@
+# 1.33.2
+* Filters should now work for all columns in the Results Table component, even for the one paused in the greyVest example i.e. `Title`.
+* Addee launch configuration for VSCode in conjunction with Chrome Debugger for components.
```
Comment (daedalus28) [inline CHANGELOG.md]: Addee -> Add

File: CHANGELOG.md [hunk 3]
```diff
@@ -1,3 +1,7 @@
+# 1.33.2
+* Filters should now work for all columns in the Results Table component, even for the one paused in the greyVest example i.e. `Title`.
```
Comment (daedalus28) [inline CHANGELOG.md]: This is should be more clear about what was fixed, e.g.

```
ResultsTable: Inline filtering on paused nodes will now be unpaused instead of silently failing
GreyVest: Added a paused node example
```

File: stories/imdb/stories/greyVest.js [hunk 4]
```diff
@@ -71,6 +71,7 @@ let tree = Contexture({
           key: 'titleText',
           type: 'tagsText',
           field: 'title',
+          paused: true,
```
Comment (daedalus28) [inline stories/imdb/stories/greyVest.js]: You should do this to a different node because this is the only `tagsText` one we have in the tree. Pick one that isn't unique like one of the facet or just add another.
